### ISSUE TITLE
managed_folders option in pagedraw json not working

### ISSUE THREAD

**Issue by khayamy001** [Pagedraw/cli#3]
It looks like `managed_folders` doesn't have any effect of the location or names of the location of the generated files. The files always appear under `src/pagedraw`.

**Comment by JamesPiskorz** [comment]
Having this issue also, BUT there is a work around, change each of the art board file's paths. Pain in the neck but works for now.

**Comment by JamesPiskorz** [comment]
Ah okay, after looking at the source, I think the option "managed folders" is used to protect files against being overwritten.

**Comment by phil-lgr** [comment]
Can we have an option to choose where to output pagedraw's files please? 🙏

**Comment by gablg1** [comment]
You can now choose default directory locations in the Pagedraw editor!
